# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
 
trigger:
  none
 
pool:
  name: "poolcapstone"
 
stages:
# Stage 1: Git Clone
- stage: GitClone
  displayName: "Clone Repository"
  jobs:
  - job: CloneJob
    displayName: "Clone Git Repository"
    steps:
    - checkout: self
      displayName: "Checkout Source Code"
 
- stage: BuildAndPush
  displayName: Build and Push stage
  jobs:
  - job: BuildAndPush
    displayName: Build and Push Docker Image
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: 'DockerRegistrysaunak'
        repository: 'python-app'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'