---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: python-app-dep
spec:
  type: LoadBalancer
  selector:
    app: python-app-pod
  ports:
    - name: python-app
      protocol: TCP
      port: 80
      targetPort: 5010
      nodePort: 0